# syntax=docker/dockerfile:1.7

FROM golang:1.25-alpine
RUN apk add --no-cache git
WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,id=gomod,target=/go/pkg/mod \
    go mod download

RUN go install github.com/air-verse/air@latest

COPY . .

EXPOSE 8080

CMD ["air"]
